// This file is autogenerated. Changes will be overwritten.
#include "BMPI5EA7AM/moc_capture_thread.cpp"
#include "BMPI5EA7AM/moc_main_window.cpp"
#include "BMPI5EA7AM/moc_preview_widget.cpp"
#include "BMPI5EA7AM/moc_settings_dialog.cpp"
